// Health Canada "Nutrient Value of Some Common Foods" (2008)
// carb_factor = carbohydrate_g / weight_g (only entries with explicit gram weights included)
// absorptionRate default: 3.0 hours (placeholder — override in personal food chart)

export const HEALTH_CANADA_FOODS = [
  // Fruits
  { name: "Apple with skin, raw", carbFactor: 0.138, absorptionRate: 3.0, source: "health_canada" },
  { name: "Apple, no skin, raw", carbFactor: 0.129, absorptionRate: 3.0, source: "health_canada" },
  { name: "Applesauce, unsweetened", carbFactor: 0.104, absorptionRate: 3.0, source: "health_canada" },
  { name: "Apricot, raw", carbFactor: 0.113, absorptionRate: 3.0, source: "health_canada" },
  { name: "Banana, raw", carbFactor: 0.230, absorptionRate: 2.5, source: "health_canada" },
  { name: "Blueberries, raw", carbFactor: 0.145, absorptionRate: 3.0, source: "health_canada" },
  { name: "Cantaloupe, raw", carbFactor: 0.082, absorptionRate: 3.0, source: "health_canada" },
  { name: "Cherries, sweet, raw", carbFactor: 0.162, absorptionRate: 3.0, source: "health_canada" },
  { name: "Cranberries, raw", carbFactor: 0.120, absorptionRate: 3.0, source: "health_canada" },
  { name: "Dates, dried", carbFactor: 0.748, absorptionRate: 2.0, source: "health_canada" },
  { name: "Figs, dried", carbFactor: 0.636, absorptionRate: 2.5, source: "health_canada" },
  { name: "Figs, raw", carbFactor: 0.192, absorptionRate: 3.0, source: "health_canada" },
  { name: "Grapefruit, raw", carbFactor: 0.084, absorptionRate: 3.0, source: "health_canada" },
  { name: "Grapes, red/green, raw", carbFactor: 0.180, absorptionRate: 2.5, source: "health_canada" },
  { name: "Honeydew melon, raw", carbFactor: 0.091, absorptionRate: 3.0, source: "health_canada" },
  { name: "Kiwifruit, raw", carbFactor: 0.150, absorptionRate: 3.0, source: "health_canada" },
  { name: "Lemon, raw", carbFactor: 0.092, absorptionRate: 3.0, source: "health_canada" },
  { name: "Mango, raw", carbFactor: 0.170, absorptionRate: 2.5, source: "health_canada" },
  { name: "Nectarine, raw", carbFactor: 0.112, absorptionRate: 3.0, source: "health_canada" },
  { name: "Orange, navel, raw", carbFactor: 0.122, absorptionRate: 3.0, source: "health_canada" },
  { name: "Papaya, raw", carbFactor: 0.109, absorptionRate: 3.0, source: "health_canada" },
  { name: "Peach, raw", carbFactor: 0.096, absorptionRate: 3.0, source: "health_canada" },
  { name: "Pear, raw", carbFactor: 0.154, absorptionRate: 3.0, source: "health_canada" },
  { name: "Pineapple, raw", carbFactor: 0.131, absorptionRate: 3.0, source: "health_canada" },
  { name: "Plum, raw", carbFactor: 0.114, absorptionRate: 3.0, source: "health_canada" },
  { name: "Prunes, dried", carbFactor: 0.638, absorptionRate: 2.5, source: "health_canada" },
  { name: "Raisins, seedless", carbFactor: 0.794, absorptionRate: 2.0, source: "health_canada" },
  { name: "Raspberries, raw", carbFactor: 0.118, absorptionRate: 3.0, source: "health_canada" },
  { name: "Strawberries, raw", carbFactor: 0.077, absorptionRate: 3.0, source: "health_canada" },
  { name: "Tangerine/mandarin, raw", carbFactor: 0.133, absorptionRate: 3.0, source: "health_canada" },
  { name: "Watermelon, raw", carbFactor: 0.076, absorptionRate: 2.5, source: "health_canada" },

  // Vegetables
  { name: "Asparagus, cooked", carbFactor: 0.039, absorptionRate: 3.0, source: "health_canada" },
  { name: "Beets, cooked", carbFactor: 0.100, absorptionRate: 3.0, source: "health_canada" },
  { name: "Broccoli, cooked", carbFactor: 0.071, absorptionRate: 3.0, source: "health_canada" },
  { name: "Brussels sprouts, cooked", carbFactor: 0.100, absorptionRate: 3.0, source: "health_canada" },
  { name: "Cabbage, raw", carbFactor: 0.058, absorptionRate: 3.0, source: "health_canada" },
  { name: "Carrots, raw", carbFactor: 0.097, absorptionRate: 3.0, source: "health_canada" },
  { name: "Carrots, cooked", carbFactor: 0.090, absorptionRate: 3.0, source: "health_canada" },
  { name: "Cauliflower, cooked", carbFactor: 0.051, absorptionRate: 3.0, source: "health_canada" },
  { name: "Celery, raw", carbFactor: 0.030, absorptionRate: 3.0, source: "health_canada" },
  { name: "Corn, sweet, cooked", carbFactor: 0.210, absorptionRate: 2.5, source: "health_canada" },
  { name: "Corn, canned", carbFactor: 0.168, absorptionRate: 2.5, source: "health_canada" },
  { name: "Cucumber, raw", carbFactor: 0.036, absorptionRate: 3.0, source: "health_canada" },
  { name: "Green beans, cooked", carbFactor: 0.079, absorptionRate: 3.0, source: "health_canada" },
  { name: "Green onion/scallion, raw", carbFactor: 0.073, absorptionRate: 3.0, source: "health_canada" },
  { name: "Green peas, cooked", carbFactor: 0.154, absorptionRate: 3.0, source: "health_canada" },
  { name: "Green pepper, raw", carbFactor: 0.066, absorptionRate: 3.0, source: "health_canada" },
  { name: "Lettuce, iceberg, raw", carbFactor: 0.028, absorptionRate: 3.0, source: "health_canada" },
  { name: "Lettuce, romaine, raw", carbFactor: 0.037, absorptionRate: 3.0, source: "health_canada" },
  { name: "Mushrooms, raw", carbFactor: 0.032, absorptionRate: 3.0, source: "health_canada" },
  { name: "Onion, raw", carbFactor: 0.093, absorptionRate: 3.0, source: "health_canada" },
  { name: "Parsnip, cooked", carbFactor: 0.192, absorptionRate: 3.0, source: "health_canada" },
  { name: "Peas, split, cooked", carbFactor: 0.211, absorptionRate: 3.5, source: "health_canada" },
  { name: "Potato, baked, with skin", carbFactor: 0.213, absorptionRate: 2.5, source: "health_canada" },
  { name: "Potato, boiled, no skin", carbFactor: 0.174, absorptionRate: 2.5, source: "health_canada" },
  { name: "Potato, mashed, with milk", carbFactor: 0.165, absorptionRate: 2.5, source: "health_canada" },
  { name: "Pumpkin, canned", carbFactor: 0.082, absorptionRate: 3.0, source: "health_canada" },
  { name: "Red pepper, raw", carbFactor: 0.063, absorptionRate: 3.0, source: "health_canada" },
  { name: "Spinach, raw", carbFactor: 0.036, absorptionRate: 3.0, source: "health_canada" },
  { name: "Spinach, cooked", carbFactor: 0.034, absorptionRate: 3.0, source: "health_canada" },
  { name: "Sweet potato, baked", carbFactor: 0.204, absorptionRate: 2.5, source: "health_canada" },
  { name: "Sweet potato, boiled", carbFactor: 0.187, absorptionRate: 2.5, source: "health_canada" },
  { name: "Tomato, raw", carbFactor: 0.039, absorptionRate: 3.0, source: "health_canada" },
  { name: "Turnip, cooked", carbFactor: 0.080, absorptionRate: 3.0, source: "health_canada" },
  { name: "Yam, baked", carbFactor: 0.375, absorptionRate: 2.5, source: "health_canada" },
  { name: "Zucchini, cooked", carbFactor: 0.036, absorptionRate: 3.0, source: "health_canada" },

  // Grains & Bread
  { name: "Bagel, plain", carbFactor: 0.492, absorptionRate: 2.0, source: "health_canada" },
  { name: "Bread, white, enriched", carbFactor: 0.491, absorptionRate: 2.0, source: "health_canada" },
  { name: "Bread, whole wheat", carbFactor: 0.432, absorptionRate: 2.5, source: "health_canada" },
  { name: "Bread, rye", carbFactor: 0.480, absorptionRate: 2.5, source: "health_canada" },
  { name: "Bread, pumpernickel", carbFactor: 0.450, absorptionRate: 3.0, source: "health_canada" },
  { name: "Bread, multigrain", carbFactor: 0.470, absorptionRate: 2.5, source: "health_canada" },
  { name: "Cracker, graham", carbFactor: 0.770, absorptionRate: 2.0, source: "health_canada" },
  { name: "Cracker, saltine/soda", carbFactor: 0.756, absorptionRate: 2.0, source: "health_canada" },
  { name: "English muffin, plain", carbFactor: 0.466, absorptionRate: 2.0, source: "health_canada" },
  { name: "Muffin, blueberry, commercial", carbFactor: 0.479, absorptionRate: 2.0, source: "health_canada" },
  { name: "Pancake, plain, homemade", carbFactor: 0.377, absorptionRate: 2.0, source: "health_canada" },
  { name: "Pita, white", carbFactor: 0.569, absorptionRate: 2.0, source: "health_canada" },
  { name: "Pita, whole wheat", carbFactor: 0.561, absorptionRate: 2.5, source: "health_canada" },
  { name: "Rice cake, plain", carbFactor: 0.797, absorptionRate: 2.0, source: "health_canada" },
  { name: "Roll, hamburger/hot dog bun", carbFactor: 0.513, absorptionRate: 2.0, source: "health_canada" },
  { name: "Tortilla, corn", carbFactor: 0.488, absorptionRate: 2.5, source: "health_canada" },
  { name: "Tortilla, flour", carbFactor: 0.569, absorptionRate: 2.0, source: "health_canada" },
  { name: "Waffle, plain", carbFactor: 0.393, absorptionRate: 2.0, source: "health_canada" },

  // Rice & Pasta
  { name: "Rice, white, long-grain, cooked", carbFactor: 0.281, absorptionRate: 2.0, source: "health_canada" },
  { name: "Rice, brown, long-grain, cooked", carbFactor: 0.230, absorptionRate: 2.5, source: "health_canada" },
  { name: "Rice, white, instant, cooked", carbFactor: 0.215, absorptionRate: 2.0, source: "health_canada" },
  { name: "Pasta, enriched, cooked", carbFactor: 0.250, absorptionRate: 2.5, source: "health_canada" },
  { name: "Pasta, whole wheat, cooked", carbFactor: 0.370, absorptionRate: 3.0, source: "health_canada" },
  { name: "Egg noodles, cooked", carbFactor: 0.250, absorptionRate: 2.5, source: "health_canada" },
  { name: "Macaroni, cooked, enriched", carbFactor: 0.250, absorptionRate: 2.5, source: "health_canada" },
  { name: "Spaghetti, cooked, enriched", carbFactor: 0.250, absorptionRate: 2.5, source: "health_canada" },

  // Cereals (dry weight)
  { name: "Cornflakes", carbFactor: 0.880, absorptionRate: 1.5, source: "health_canada" },
  { name: "Cream of wheat, cooked", carbFactor: 0.124, absorptionRate: 2.0, source: "health_canada" },
  { name: "Granola, plain", carbFactor: 0.579, absorptionRate: 2.5, source: "health_canada" },
  { name: "Oatmeal, cooked with water", carbFactor: 0.117, absorptionRate: 3.0, source: "health_canada" },
  { name: "Oats, rolled, dry", carbFactor: 0.668, absorptionRate: 3.0, source: "health_canada" },
  { name: "Puffed rice cereal", carbFactor: 0.874, absorptionRate: 1.5, source: "health_canada" },
  { name: "Raisin bran cereal", carbFactor: 0.736, absorptionRate: 2.0, source: "health_canada" },
  { name: "Shredded wheat cereal", carbFactor: 0.817, absorptionRate: 2.5, source: "health_canada" },

  // Legumes
  { name: "Baked beans, canned", carbFactor: 0.201, absorptionRate: 4.0, source: "health_canada" },
  { name: "Black beans, cooked", carbFactor: 0.237, absorptionRate: 4.0, source: "health_canada" },
  { name: "Chickpeas/garbanzo, cooked", carbFactor: 0.274, absorptionRate: 4.0, source: "health_canada" },
  { name: "Kidney beans, red, cooked", carbFactor: 0.228, absorptionRate: 4.0, source: "health_canada" },
  { name: "Lentils, cooked", carbFactor: 0.200, absorptionRate: 4.0, source: "health_canada" },
  { name: "Lima beans, cooked", carbFactor: 0.208, absorptionRate: 4.0, source: "health_canada" },
  { name: "Navy beans, cooked", carbFactor: 0.268, absorptionRate: 4.0, source: "health_canada" },
  { name: "Pinto beans, cooked", carbFactor: 0.223, absorptionRate: 4.0, source: "health_canada" },
  { name: "Soybeans, cooked", carbFactor: 0.099, absorptionRate: 4.0, source: "health_canada" },
  { name: "Tofu, firm", carbFactor: 0.022, absorptionRate: 4.0, source: "health_canada" },

  // Dairy
  { name: "Milk, whole (3.25%)", carbFactor: 0.049, absorptionRate: 2.5, source: "health_canada" },
  { name: "Milk, 2%", carbFactor: 0.049, absorptionRate: 2.5, source: "health_canada" },
  { name: "Milk, 1%", carbFactor: 0.050, absorptionRate: 2.5, source: "health_canada" },
  { name: "Milk, skim/non-fat", carbFactor: 0.051, absorptionRate: 2.5, source: "health_canada" },
  { name: "Yogurt, plain, whole milk", carbFactor: 0.048, absorptionRate: 3.0, source: "health_canada" },
  { name: "Yogurt, plain, low-fat", carbFactor: 0.073, absorptionRate: 3.0, source: "health_canada" },
  { name: "Yogurt, fruit, low-fat", carbFactor: 0.191, absorptionRate: 2.5, source: "health_canada" },
  { name: "Yogurt, Greek, plain, non-fat", carbFactor: 0.038, absorptionRate: 3.0, source: "health_canada" },
  { name: "Ice cream, vanilla, regular", carbFactor: 0.232, absorptionRate: 2.5, source: "health_canada" },
  { name: "Ice cream, chocolate, regular", carbFactor: 0.286, absorptionRate: 2.5, source: "health_canada" },

  // Snacks & Sweets
  { name: "Chocolate, milk", carbFactor: 0.600, absorptionRate: 2.0, source: "health_canada" },
  { name: "Chocolate, dark (70-85%)", carbFactor: 0.460, absorptionRate: 2.5, source: "health_canada" },
  { name: "Cookies, chocolate chip", carbFactor: 0.699, absorptionRate: 2.0, source: "health_canada" },
  { name: "Cookies, oatmeal", carbFactor: 0.703, absorptionRate: 2.0, source: "health_canada" },
  { name: "Cookies, shortbread", carbFactor: 0.729, absorptionRate: 2.0, source: "health_canada" },
  { name: "Corn chips", carbFactor: 0.635, absorptionRate: 2.0, source: "health_canada" },
  { name: "Doughnut, cake type", carbFactor: 0.510, absorptionRate: 2.0, source: "health_canada" },
  { name: "Doughnut, glazed/yeast", carbFactor: 0.452, absorptionRate: 2.0, source: "health_canada" },
  { name: "French fries, fast food", carbFactor: 0.373, absorptionRate: 2.0, source: "health_canada" },
  { name: "Fruit snacks/gummies", carbFactor: 0.810, absorptionRate: 1.5, source: "health_canada" },
  { name: "Honey", carbFactor: 0.824, absorptionRate: 1.5, source: "health_canada" },
  { name: "Jam/preserves", carbFactor: 0.688, absorptionRate: 1.5, source: "health_canada" },
  { name: "Maple syrup", carbFactor: 0.671, absorptionRate: 1.5, source: "health_canada" },
  { name: "Popcorn, air-popped", carbFactor: 0.778, absorptionRate: 2.0, source: "health_canada" },
  { name: "Potato chips", carbFactor: 0.501, absorptionRate: 2.0, source: "health_canada" },
  { name: "Pretzels", carbFactor: 0.793, absorptionRate: 2.0, source: "health_canada" },
  { name: "Sugar, white, granulated", carbFactor: 1.000, absorptionRate: 1.0, source: "health_canada" },
  { name: "Sugar, brown, packed", carbFactor: 0.982, absorptionRate: 1.0, source: "health_canada" },
  { name: "Syrup, corn, dark", carbFactor: 0.765, absorptionRate: 1.5, source: "health_canada" },
  { name: "Tortilla chips", carbFactor: 0.643, absorptionRate: 2.0, source: "health_canada" },

  // Juices & Beverages (per 100g = 100mL for liquids)
  { name: "Apple juice, unsweetened", carbFactor: 0.114, absorptionRate: 1.5, source: "health_canada" },
  { name: "Cranberry juice cocktail", carbFactor: 0.121, absorptionRate: 1.5, source: "health_canada" },
  { name: "Grape juice, unsweetened", carbFactor: 0.150, absorptionRate: 1.5, source: "health_canada" },
  { name: "Grapefruit juice, unsweetened", carbFactor: 0.090, absorptionRate: 1.5, source: "health_canada" },
  { name: "Orange juice, unsweetened", carbFactor: 0.104, absorptionRate: 1.5, source: "health_canada" },
  { name: "Pineapple juice, unsweetened", carbFactor: 0.133, absorptionRate: 1.5, source: "health_canada" },
  { name: "Tomato juice", carbFactor: 0.042, absorptionRate: 2.0, source: "health_canada" },

  // Prepared / Mixed foods
  { name: "Pizza, cheese, regular crust", carbFactor: 0.310, absorptionRate: 2.5, source: "health_canada" },
  { name: "Pizza, pepperoni, regular crust", carbFactor: 0.296, absorptionRate: 2.5, source: "health_canada" },
  { name: "Soup, tomato, canned with water", carbFactor: 0.068, absorptionRate: 2.5, source: "health_canada" },
  { name: "Soup, chicken noodle, canned with water", carbFactor: 0.056, absorptionRate: 2.5, source: "health_canada" },

  // Nuts & Seeds
  { name: "Almonds, dry roasted", carbFactor: 0.198, absorptionRate: 4.0, source: "health_canada" },
  { name: "Cashews, dry roasted", carbFactor: 0.324, absorptionRate: 3.5, source: "health_canada" },
  { name: "Peanuts, dry roasted", carbFactor: 0.215, absorptionRate: 4.0, source: "health_canada" },
  { name: "Peanut butter, smooth", carbFactor: 0.196, absorptionRate: 4.0, source: "health_canada" },
  { name: "Pecans", carbFactor: 0.139, absorptionRate: 4.0, source: "health_canada" },
  { name: "Sunflower seeds, dry roasted", carbFactor: 0.269, absorptionRate: 3.5, source: "health_canada" },
  { name: "Walnuts", carbFactor: 0.138, absorptionRate: 4.0, source: "health_canada" },
];

// Excluded foods logged separately in data/health_canada_review.xlsx
// Exclusion reasons: volumetric measure only, 'tr' or N/A carbs, ambiguous weight